//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopMachine.Web.GameViewer.DeleteGameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeleteGameService.IDeleteServices")]
    public interface IDeleteServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeleteServices/DeleteGameXML", ReplyAction="http://tempuri.org/IDeleteServices/DeleteGameXMLResponse")]
        bool DeleteGameXML(string fn);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeleteServicesChannel : TopMachine.Web.GameViewer.DeleteGameService.IDeleteServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteServicesClient : System.ServiceModel.ClientBase<TopMachine.Web.GameViewer.DeleteGameService.IDeleteServices>, TopMachine.Web.GameViewer.DeleteGameService.IDeleteServices {
        
        public DeleteServicesClient() {
        }
        
        public DeleteServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeleteServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DeleteGameXML(string fn) {
            return base.Channel.DeleteGameXML(fn);
        }
    }
}
