//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Topping.Core.Data.Db4o
{
    public partial class GameRanking
    {
        #region Primitive Properties
    
        public virtual int Year
        {
            get;
            set;
        }
    
        public virtual int Month
        {
            get;
            set;
        }
    
        public virtual System.Guid ConfigGameId
        {
            get;
            set;
        }
    
        public virtual System.Guid Playerid
        {
            get;
            set;
        }
    
        public virtual double Percentage
        {
            get;
            set;
        }
    
        public virtual int NbParties
        {
            get;
            set;
        }
    
        public virtual double LostTops
        {
            get;
            set;
        }
    
        public virtual int Time
        {
            get;
            set;
        }
    
        public virtual int TotalTops
        {
            get;
            set;
        }
    
        public virtual int Position
        {
            get;
            set;
        }
    
        public virtual int Serie
        {
            get;
            set;
        }
    
        public virtual int PlayerTop
        {
            get;
            set;
        }
    
        public virtual int GameTop
        {
            get;
            set;
        }
    
        public virtual int Selection
        {
            get;
            set;
        }
    
        public virtual int BestTime
        {
            get;
            set;
        }
    
        public virtual double BestScore
        {
            get;
            set;
        }

        #endregion
    }
}
