//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Topping.Core.Data.Db4o
{
    public partial class GamesDetail
    {
        #region Primitive Properties

        public virtual System.Guid GameConfigId
        {
            get;
            set;
        }

        public virtual System.Guid GameId
        {
            get;
            set;
        }
    
        public virtual System.Guid UserId
        {
            get;
            set;
        }
    
        public virtual string DetailXml
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Total
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Solos
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Warnings
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Time
        {
            get;
            set;
        }
    
        public virtual Nullable<double> Percentage
        {
            get;
            set;
        }
    
        public virtual Nullable<long> TopLost
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Top
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Negative
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Selection
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Rating
        {
            get;
            set;
        }
    
        public virtual Nullable<long> Status
        {
            get;
            set;
        }
    
        public virtual System.DateTime Date
        {
            get;
            set;
        }

        #endregion
    }
}
