//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Db4objects.Db4o.Config.Attributes;

namespace TopMachine.Training.DAL.fdbo
{
    public partial class Config
    {
        #region Primitive Properties


        public virtual long ID
        {
            get;
            set;
        }
    
        public virtual string XMLConfig
        {
            get;
            set;
        }
    
        public virtual string XMLPlay
        {
            get;
            set;
        }

        #endregion
    }
}
