//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TopMachine.Training.DAL.fdbo
{
    public partial class Session
    {
        #region Primitive Properties
    
        public virtual System.Guid DateTime
        {
            get;
            set;
        }
    
        public virtual long RoundsFound
        {
            get;
            set;
        }
    
        public virtual long RoundsTotal
        {
            get;
            set;
        }
    
        public virtual long WordsFound
        {
            get;
            set;
        }
    
        public virtual long WordsTotal
        {
            get;
            set;
        }
    
        public virtual long TotalTime
        {
            get;
            set;
        }

        #endregion
    }
}
