//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TopMachine.Web.GameViewer.BLL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ToppingGamesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ToppingGamesEntities object using the connection string found in the 'ToppingGamesEntities' section of the application configuration file.
        /// </summary>
        public ToppingGamesEntities() : base("name=ToppingGamesEntities", "ToppingGamesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ToppingGamesEntities object.
        /// </summary>
        public ToppingGamesEntities(string connectionString) : base(connectionString, "ToppingGamesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ToppingGamesEntities object.
        /// </summary>
        public ToppingGamesEntities(EntityConnection connection) : base(connection, "ToppingGamesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameCollector> GameCollectors
        {
            get
            {
                if ((_GameCollectors == null))
                {
                    _GameCollectors = base.CreateObjectSet<GameCollector>("GameCollectors");
                }
                return _GameCollectors;
            }
        }
        private ObjectSet<GameCollector> _GameCollectors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameConfig> GameConfigs
        {
            get
            {
                if ((_GameConfigs == null))
                {
                    _GameConfigs = base.CreateObjectSet<GameConfig>("GameConfigs");
                }
                return _GameConfigs;
            }
        }
        private ObjectSet<GameConfig> _GameConfigs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameDetail> GameDetails
        {
            get
            {
                if ((_GameDetails == null))
                {
                    _GameDetails = base.CreateObjectSet<GameDetail>("GameDetails");
                }
                return _GameDetails;
            }
        }
        private ObjectSet<GameDetail> _GameDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameRanking> GameRankings
        {
            get
            {
                if ((_GameRankings == null))
                {
                    _GameRankings = base.CreateObjectSet<GameRanking>("GameRankings");
                }
                return _GameRankings;
            }
        }
        private ObjectSet<GameRanking> _GameRankings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Game> Games
        {
            get
            {
                if ((_Games == null))
                {
                    _Games = base.CreateObjectSet<Game>("Games");
                }
                return _Games;
            }
        }
        private ObjectSet<Game> _Games;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameSet> GameSets
        {
            get
            {
                if ((_GameSets == null))
                {
                    _GameSets = base.CreateObjectSet<GameSet>("GameSets");
                }
                return _GameSets;
            }
        }
        private ObjectSet<GameSet> _GameSets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameType> GameTypes
        {
            get
            {
                if ((_GameTypes == null))
                {
                    _GameTypes = base.CreateObjectSet<GameType>("GameTypes");
                }
                return _GameTypes;
            }
        }
        private ObjectSet<GameType> _GameTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GameShort> GameShorts
        {
            get
            {
                if ((_GameShorts == null))
                {
                    _GameShorts = base.CreateObjectSet<GameShort>("GameShorts");
                }
                return _GameShorts;
            }
        }
        private ObjectSet<GameShort> _GameShorts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameCollectors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameCollectors(GameCollector gameCollector)
        {
            base.AddObject("GameCollectors", gameCollector);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameConfigs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameConfigs(GameConfig gameConfig)
        {
            base.AddObject("GameConfigs", gameConfig);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameDetails(GameDetail gameDetail)
        {
            base.AddObject("GameDetails", gameDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameRankings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameRankings(GameRanking gameRanking)
        {
            base.AddObject("GameRankings", gameRanking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Games EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGames(Game game)
        {
            base.AddObject("Games", game);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameSets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameSets(GameSet gameSet)
        {
            base.AddObject("GameSets", gameSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameTypes(GameType gameType)
        {
            base.AddObject("GameTypes", gameType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GameShorts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGameShorts(GameShort gameShort)
        {
            base.AddObject("GameShorts", gameShort);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="llequehot6793com6306_topmachineModel", Name="Game")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Game : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Game object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Game CreateGame(global::System.Int64 id)
        {
            Game game = new Game();
            game.Id = id;
            return game;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SetId
        {
            get
            {
                return _SetId;
            }
            set
            {
                OnSetIdChanging(value);
                ReportPropertyChanging("SetId");
                _SetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SetId");
                OnSetIdChanged();
            }
        }
        private Nullable<global::System.Int64> _SetId;
        partial void OnSetIdChanging(Nullable<global::System.Int64> value);
        partial void OnSetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GameXml
        {
            get
            {
                return _GameXml;
            }
            set
            {
                OnGameXmlChanging(value);
                ReportPropertyChanging("GameXml");
                _GameXml = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GameXml");
                OnGameXmlChanged();
            }
        }
        private global::System.String _GameXml;
        partial void OnGameXmlChanging(global::System.String value);
        partial void OnGameXmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="llequehot6793com6306_topmachineModel", Name="GameCollector")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameCollector : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameCollector object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static GameCollector CreateGameCollector(global::System.Int64 id)
        {
            GameCollector gameCollector = new GameCollector();
            gameCollector.Id = id;
            return gameCollector;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int64> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int64> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdate;
        partial void OnLastUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="llequehot6793com6306_topmachineModel", Name="GameConfig")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameConfig : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameConfig object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="xml">Initial value of the Xml property.</param>
        public static GameConfig CreateGameConfig(global::System.Int64 id, global::System.String xml)
        {
            GameConfig gameConfig = new GameConfig();
            gameConfig.Id = id;
            gameConfig.Xml = xml;
            return gameConfig;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Xml
        {
            get
            {
                return _Xml;
            }
            set
            {
                OnXmlChanging(value);
                ReportPropertyChanging("Xml");
                _Xml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Xml");
                OnXmlChanged();
            }
        }
        private global::System.String _Xml;
        partial void OnXmlChanging(global::System.String value);
        partial void OnXmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> OriginalId
        {
            get
            {
                return _OriginalId;
            }
            set
            {
                OnOriginalIdChanging(value);
                ReportPropertyChanging("OriginalId");
                _OriginalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OriginalId");
                OnOriginalIdChanged();
            }
        }
        private Nullable<global::System.Guid> _OriginalId;
        partial void OnOriginalIdChanging(Nullable<global::System.Guid> value);
        partial void OnOriginalIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="llequehot6793com6306_topmachineModel", Name="GameDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameDetail object.
        /// </summary>
        /// <param name="gameId">Initial value of the GameId property.</param>
        /// <param name="pseudo">Initial value of the Pseudo property.</param>
        public static GameDetail CreateGameDetail(global::System.Int64 gameId, global::System.String pseudo)
        {
            GameDetail gameDetail = new GameDetail();
            gameDetail.GameId = gameId;
            gameDetail.Pseudo = pseudo;
            return gameDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 GameId
        {
            get
            {
                return _GameId;
            }
            set
            {
                if (_GameId != value)
                {
                    OnGameIdChanging(value);
                    ReportPropertyChanging("GameId");
                    _GameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GameId");
                    OnGameIdChanged();
                }
            }
        }
        private global::System.Int64 _GameId;
        partial void OnGameIdChanging(global::System.Int64 value);
        partial void OnGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pseudo
        {
            get
            {
                return _Pseudo;
            }
            set
            {
                if (_Pseudo != value)
                {
                    OnPseudoChanging(value);
                    ReportPropertyChanging("Pseudo");
                    _Pseudo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Pseudo");
                    OnPseudoChanged();
                }
            }
        }
        private global::System.String _Pseudo;
        partial void OnPseudoChanging(global::System.String value);
        partial void OnPseudoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private Nullable<global::System.Int32> _Total;
        partial void OnTotalChanging(Nullable<global::System.Int32> value);
        partial void OnTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Solos
        {
            get
            {
                return _Solos;
            }
            set
            {
                OnSolosChanging(value);
                ReportPropertyChanging("Solos");
                _Solos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Solos");
                OnSolosChanged();
            }
        }
        private Nullable<global::System.Int32> _Solos;
        partial void OnSolosChanging(Nullable<global::System.Int32> value);
        partial void OnSolosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Warnings
        {
            get
            {
                return _Warnings;
            }
            set
            {
                OnWarningsChanging(value);
                ReportPropertyChanging("Warnings");
                _Warnings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Warnings");
                OnWarningsChanged();
            }
        }
        private Nullable<global::System.Int32> _Warnings;
        partial void OnWarningsChanging(Nullable<global::System.Int32> value);
        partial void OnWarningsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _Time;
        partial void OnTimeChanging(Nullable<global::System.Int32> value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Percentage
        {
            get
            {
                return _Percentage;
            }
            set
            {
                OnPercentageChanging(value);
                ReportPropertyChanging("Percentage");
                _Percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Percentage");
                OnPercentageChanged();
            }
        }
        private Nullable<global::System.Double> _Percentage;
        partial void OnPercentageChanging(Nullable<global::System.Double> value);
        partial void OnPercentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TopLost
        {
            get
            {
                return _TopLost;
            }
            set
            {
                OnTopLostChanging(value);
                ReportPropertyChanging("TopLost");
                _TopLost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TopLost");
                OnTopLostChanged();
            }
        }
        private Nullable<global::System.Int32> _TopLost;
        partial void OnTopLostChanging(Nullable<global::System.Int32> value);
        partial void OnTopLostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Top
        {
            get
            {
                return _Top;
            }
            set
            {
                OnTopChanging(value);
                ReportPropertyChanging("Top");
                _Top = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Top");
                OnTopChanged();
            }
        }
        private Nullable<global::System.Boolean> _Top;
        partial void OnTopChanging(Nullable<global::System.Boolean> value);
        partial void OnTopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Negative
        {
            get
            {
                return _Negative;
            }
            set
            {
                OnNegativeChanging(value);
                ReportPropertyChanging("Negative");
                _Negative = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Negative");
                OnNegativeChanged();
            }
        }
        private Nullable<global::System.Int32> _Negative;
        partial void OnNegativeChanging(Nullable<global::System.Int32> value);
        partial void OnNegativeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Selection
        {
            get
            {
                return _Selection;
            }
            set
            {
                OnSelectionChanging(value);
                ReportPropertyChanging("Selection");
                _Selection = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Selection");
                OnSelectionChanged();
            }
        }
        private Nullable<global::System.Int32> _Selection;
        partial void OnSelectionChanging(Nullable<global::System.Int32> value);
        partial void OnSelectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private Nullable<global::System.Int32> _Rating;
        partial void OnRatingChanging(Nullable<global::System.Int32> value);
        partial void OnRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int32> value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RoundsXml
        {
            get
            {
                return _RoundsXml;
            }
            set
            {
                OnRoundsXmlChanging(value);
                ReportPropertyChanging("RoundsXml");
                _RoundsXml = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RoundsXml");
                OnRoundsXmlChanged();
            }
        }
        private global::System.String _RoundsXml;
        partial void OnRoundsXmlChanging(global::System.String value);
        partial void OnRoundsXmlChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="llequehot6793com6306_topmachineModel", Name="GameRanking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameRanking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameRanking object.
        /// </summary>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="month">Initial value of the Month property.</param>
        /// <param name="configGameId">Initial value of the ConfigGameId property.</param>
        /// <param name="pseudo">Initial value of the Pseudo property.</param>
        public static GameRanking CreateGameRanking(global::System.Int32 year, global::System.Int32 month, global::System.Int32 configGameId, global::System.String pseudo)
        {
            GameRanking gameRanking = new GameRanking();
            gameRanking.Year = year;
            gameRanking.Month = month;
            gameRanking.ConfigGameId = configGameId;
            gameRanking.Pseudo = pseudo;
            return gameRanking;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                if (_Year != value)
                {
                    OnYearChanging(value);
                    ReportPropertyChanging("Year");
                    _Year = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Year");
                    OnYearChanged();
                }
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Month
        {
            get
            {
                return _Month;
            }
            set
            {
                if (_Month != value)
                {
                    OnMonthChanging(value);
                    ReportPropertyChanging("Month");
                    _Month = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Month");
                    OnMonthChanged();
                }
            }
        }
        private global::System.Int32 _Month;
        partial void OnMonthChanging(global::System.Int32 value);
        partial void OnMonthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConfigGameId
        {
            get
            {
                return _ConfigGameId;
            }
            set
            {
                if (_ConfigGameId != value)
                {
                    OnConfigGameIdChanging(value);
                    ReportPropertyChanging("ConfigGameId");
                    _ConfigGameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConfigGameId");
                    OnConfigGameIdChanged();
                }
            }
        }
        private global::System.Int32 _ConfigGameId;
        partial void OnConfigGameIdChanging(global::System.Int32 value);
        partial void OnConfigGameIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pseudo
        {
            get
            {
                return _Pseudo;
            }
            set
            {
                if (_Pseudo != value)
                {
                    OnPseudoChanging(value);
                    ReportPropertyChanging("Pseudo");
                    _Pseudo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Pseudo");
                    OnPseudoChanged();
                }
            }
        }
        private global::System.String _Pseudo;
        partial void OnPseudoChanging(global::System.String value);
        partial void OnPseudoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Percentage
        {
            get
            {
                return _Percentage;
            }
            set
            {
                OnPercentageChanging(value);
                ReportPropertyChanging("Percentage");
                _Percentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Percentage");
                OnPercentageChanged();
            }
        }
        private Nullable<global::System.Double> _Percentage;
        partial void OnPercentageChanging(Nullable<global::System.Double> value);
        partial void OnPercentageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NbParties
        {
            get
            {
                return _NbParties;
            }
            set
            {
                OnNbPartiesChanging(value);
                ReportPropertyChanging("NbParties");
                _NbParties = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NbParties");
                OnNbPartiesChanged();
            }
        }
        private Nullable<global::System.Int32> _NbParties;
        partial void OnNbPartiesChanging(Nullable<global::System.Int32> value);
        partial void OnNbPartiesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LostTops
        {
            get
            {
                return _LostTops;
            }
            set
            {
                OnLostTopsChanging(value);
                ReportPropertyChanging("LostTops");
                _LostTops = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LostTops");
                OnLostTopsChanged();
            }
        }
        private Nullable<global::System.Int32> _LostTops;
        partial void OnLostTopsChanging(Nullable<global::System.Int32> value);
        partial void OnLostTopsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _Time;
        partial void OnTimeChanging(Nullable<global::System.Int32> value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalTops
        {
            get
            {
                return _TotalTops;
            }
            set
            {
                OnTotalTopsChanging(value);
                ReportPropertyChanging("TotalTops");
                _TotalTops = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalTops");
                OnTotalTopsChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalTops;
        partial void OnTotalTopsChanging(Nullable<global::System.Int32> value);
        partial void OnTotalTopsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private Nullable<global::System.Int32> _Position;
        partial void OnPositionChanging(Nullable<global::System.Int32> value);
        partial void OnPositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PlayerTop
        {
            get
            {
                return _PlayerTop;
            }
            set
            {
                OnPlayerTopChanging(value);
                ReportPropertyChanging("PlayerTop");
                _PlayerTop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayerTop");
                OnPlayerTopChanged();
            }
        }
        private Nullable<global::System.Int32> _PlayerTop;
        partial void OnPlayerTopChanging(Nullable<global::System.Int32> value);
        partial void OnPlayerTopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GameTop
        {
            get
            {
                return _GameTop;
            }
            set
            {
                OnGameTopChanging(value);
                ReportPropertyChanging("GameTop");
                _GameTop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameTop");
                OnGameTopChanged();
            }
        }
        private Nullable<global::System.Int32> _GameTop;
        partial void OnGameTopChanging(Nullable<global::System.Int32> value);
        partial void OnGameTopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Selection
        {
            get
            {
                return _Selection;
            }
            set
            {
                OnSelectionChanging(value);
                ReportPropertyChanging("Selection");
                _Selection = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Selection");
                OnSelectionChanged();
            }
        }
        private Nullable<global::System.Int32> _Selection;
        partial void OnSelectionChanging(Nullable<global::System.Int32> value);
        partial void OnSelectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BestTime
        {
            get
            {
                return _BestTime;
            }
            set
            {
                OnBestTimeChanging(value);
                ReportPropertyChanging("BestTime");
                _BestTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BestTime");
                OnBestTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _BestTime;
        partial void OnBestTimeChanging(Nullable<global::System.Int32> value);
        partial void OnBestTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BestScore
        {
            get
            {
                return _BestScore;
            }
            set
            {
                OnBestScoreChanging(value);
                ReportPropertyChanging("BestScore");
                _BestScore = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BestScore");
                OnBestScoreChanged();
            }
        }
        private Nullable<global::System.Double> _BestScore;
        partial void OnBestScoreChanging(Nullable<global::System.Double> value);
        partial void OnBestScoreChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="llequehot6793com6306_topmachineModel", Name="GameSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameSet object.
        /// </summary>
        /// <param name="annee">Initial value of the Annee property.</param>
        /// <param name="mois">Initial value of the Mois property.</param>
        /// <param name="jour">Initial value of the Jour property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        public static GameSet CreateGameSet(global::System.Int32 annee, global::System.Int32 mois, global::System.Int32 jour, global::System.Int64 id)
        {
            GameSet gameSet = new GameSet();
            gameSet.Annee = annee;
            gameSet.Mois = mois;
            gameSet.Jour = jour;
            gameSet.Id = id;
            return gameSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Annee
        {
            get
            {
                return _Annee;
            }
            set
            {
                OnAnneeChanging(value);
                ReportPropertyChanging("Annee");
                _Annee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Annee");
                OnAnneeChanged();
            }
        }
        private global::System.Int32 _Annee;
        partial void OnAnneeChanging(global::System.Int32 value);
        partial void OnAnneeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Mois
        {
            get
            {
                return _Mois;
            }
            set
            {
                OnMoisChanging(value);
                ReportPropertyChanging("Mois");
                _Mois = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mois");
                OnMoisChanged();
            }
        }
        private global::System.Int32 _Mois;
        partial void OnMoisChanging(global::System.Int32 value);
        partial void OnMoisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Jour
        {
            get
            {
                return _Jour;
            }
            set
            {
                OnJourChanging(value);
                ReportPropertyChanging("Jour");
                _Jour = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Jour");
                OnJourChanged();
            }
        }
        private global::System.Int32 _Jour;
        partial void OnJourChanging(global::System.Int32 value);
        partial void OnJourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> GameCollectorId
        {
            get
            {
                return _GameCollectorId;
            }
            set
            {
                OnGameCollectorIdChanging(value);
                ReportPropertyChanging("GameCollectorId");
                _GameCollectorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GameCollectorId");
                OnGameCollectorIdChanged();
            }
        }
        private Nullable<global::System.Int64> _GameCollectorId;
        partial void OnGameCollectorIdChanging(Nullable<global::System.Int64> value);
        partial void OnGameCollectorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdate;
        partial void OnLastUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="llequehot6793com6306_topmachineModel", Name="GameShort")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameShort : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameShort object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static GameShort CreateGameShort(global::System.Int64 id)
        {
            GameShort gameShort = new GameShort();
            gameShort.Id = id;
            return gameShort;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> SetId
        {
            get
            {
                return _SetId;
            }
            set
            {
                OnSetIdChanging(value);
                ReportPropertyChanging("SetId");
                _SetId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SetId");
                OnSetIdChanged();
            }
        }
        private Nullable<global::System.Int64> _SetId;
        partial void OnSetIdChanging(Nullable<global::System.Int64> value);
        partial void OnSetIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="llequehot6793com6306_topmachineModel", Name="GameType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GameType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GameType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static GameType CreateGameType(global::System.Int32 id)
        {
            GameType gameType = new GameType();
            gameType.Id = id;
            return gameType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();

        #endregion
    
    }

    #endregion
    
}
