//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topping.Core.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRankings
    {
        public int Year { get; set; }
        public int Month { get; set; }
        public System.Guid ConfigGameId { get; set; }
        public System.Guid Playerid { get; set; }
        public double Percentage { get; set; }
        public int NbParties { get; set; }
        public double LostTops { get; set; }
        public int Time { get; set; }
        public int TotalTops { get; set; }
        public int Position { get; set; }
        public int Serie { get; set; }
        public int PlayerTop { get; set; }
        public int GameTop { get; set; }
        public int Selection { get; set; }
        public int BestTime { get; set; }
        public double BestScore { get; set; }
    }
}
