//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topping.Core.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public System.Guid GameId { get; set; }
        public System.Guid GameConfigId { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public string GameXml { get; set; }
        public string Name { get; set; }
    }
}
