//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topping.Core.Data.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TopMachineDBEntities : DbContext
    {
        public TopMachineDBEntities()
            : base("name=TopMachineDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Users> Users { get; set; }
        public DbSet<GameConfigs> GameConfigs { get; set; }
        public DbSet<GameRankings> GameRankings { get; set; }
        public DbSet<Games> Games { get; set; }
        public DbSet<GamesDetail> GamesDetail { get; set; }
    }
}
