// T4 code generation is enabled for model 'D:\Ict7\Sample\Test topmachine\TopMachine.Desktop.2012\Topping\TopMachine.Desktop.DAL\DicoModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DicoFRModel", "FK_Mots_0", "Dico", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TopMachine.Topping.DAL.Dico), "Mots", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TopMachine.Topping.DAL.Mot), true)]

#endregion

namespace TopMachine.Topping.DAL
{
	#region Contexts

	/// <summary>
	/// No Metadata Documentation available.
	/// </summary>
	public partial class DicoFREntities : ObjectContext
	{
		#region Constructors

		/// <summary>
		/// Initializes a new DicoFREntities object using the connection string found in the 'DicoFREntities' section of the application configuration file.
		/// </summary>
		public DicoFREntities() : base("name=DicoFREntities", "DicoFREntities")
		{
			OnContextCreated();
		}

		/// <summary>
		/// Initialize a new DicoFREntities object.
		/// </summary>
		public DicoFREntities(string connectionString) : base(connectionString, "DicoFREntities")
		{
			OnContextCreated();
		}

		/// <summary>
		/// Initialize a new DicoFREntities object.
		/// </summary>
		public DicoFREntities(EntityConnection connection) : base(connection, "DicoFREntities")
		{
			OnContextCreated();
		}

		#endregion

		#region Partial Methods

		partial void OnContextCreated();

		#endregion

		#region ObjectSet Properties

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		public ObjectSet<Dico> Dicoes
		{
			get
			{
				if ((_Dicoes == null))
				{
					_Dicoes = base.CreateObjectSet<Dico>("Dicoes");
				}
				return _Dicoes;
			}
		}
		private ObjectSet<Dico> _Dicoes;

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		public ObjectSet<Mot> Mots
		{
			get
			{
				if ((_Mots == null))
				{
					_Mots = base.CreateObjectSet<Mot>("Mots");
				}
				return _Mots;
			}
		}
		private ObjectSet<Mot> _Mots;

		#endregion

		#region AddTo Methods

		/// <summary>
		/// Deprecated Method for adding a new object to the Dicoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		/// </summary>
		public void AddToDicoes(Dico dico)
		{
			base.AddObject("Dicoes", dico);
		}

		/// <summary>
		/// Deprecated Method for adding a new object to the Mots EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		/// </summary>
		public void AddToMots(Mot mot)
		{
			base.AddObject("Mots", mot);
		}

		#endregion

	}

	#endregion

	#region Entities

	/// <summary>
	/// No Metadata Documentation available.
	/// </summary>
	[EdmEntityTypeAttribute(NamespaceName = "DicoFRModel", Name = "Dico")]
	[Serializable()]
	[DataContractAttribute(IsReference = true)]
	public partial class Dico : EntityObject
	{
		#region Factory Method

		/// <summary>
		/// Create a new Dico object.
		/// </summary>
		/// <param name="id">Initial value of the ID property.</param>
		/// <param name="isInvariable">Initial value of the isInvariable property.</param>
		/// <param name="isListe">Initial value of the isListe property.</param>
		/// <param name="isAccord">Initial value of the isAccord property.</param>
		/// <param name="isExported">Initial value of the isExported property.</param>
		/// <param name="isODS5">Initial value of the isODS5 property.</param>
		public static Dico CreateDico(global::System.Int64 id, global::System.Boolean isInvariable, global::System.Boolean isListe, global::System.Boolean isAccord, global::System.Boolean isExported, global::System.Boolean isODS5)
		{
			Dico dico = new Dico();
			dico.ID = id;
			dico.isInvariable = isInvariable;
			dico.isListe = isListe;
			dico.isAccord = isAccord;
			dico.isExported = isExported;
			dico.isODS5 = isODS5;
			return dico;
		}

		#endregion

		#region Primitive Properties

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
		[DataMemberAttribute()]
		public global::System.Int64 ID
		{
			get
			{
				return _ID;
			}
			set
			{
				if (_ID != value)
				{
					OnIDChanging(value);
					ReportPropertyChanging("ID");
					_ID = StructuralObject.SetValidValue(value);
					ReportPropertyChanged("ID");
					OnIDChanged();
				}
			}
		}
		private global::System.Int64 _ID;
		partial void OnIDChanging(global::System.Int64 value);
		partial void OnIDChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public global::System.String Key
		{
			get
			{
				return _Key;
			}
			set
			{
				OnKeyChanging(value);
				ReportPropertyChanging("Key");
				_Key = StructuralObject.SetValidValue(value, true);
				ReportPropertyChanged("Key");
				OnKeyChanged();
			}
		}
		private global::System.String _Key;
		partial void OnKeyChanging(global::System.String value);
		partial void OnKeyChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public global::System.String Mot
		{
			get
			{
				return _Mot;
			}
			set
			{
				OnMotChanging(value);
				ReportPropertyChanging("Mot");
				_Mot = StructuralObject.SetValidValue(value, true);
				ReportPropertyChanged("Mot");
				OnMotChanged();
			}
		}
		private global::System.String _Mot;
		partial void OnMotChanging(global::System.String value);
		partial void OnMotChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public global::System.String Genre
		{
			get
			{
				return _Genre;
			}
			set
			{
				OnGenreChanging(value);
				ReportPropertyChanging("Genre");
				_Genre = StructuralObject.SetValidValue(value, true);
				ReportPropertyChanged("Genre");
				OnGenreChanged();
			}
		}
		private global::System.String _Genre;
		partial void OnGenreChanging(global::System.String value);
		partial void OnGenreChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public global::System.String Definition
		{
			get
			{
				return _Definition;
			}
			set
			{
				OnDefinitionChanging(value);
				ReportPropertyChanging("Definition");
				_Definition = StructuralObject.SetValidValue(value, true);
				ReportPropertyChanged("Definition");
				OnDefinitionChanged();
			}
		}
		private global::System.String _Definition;
		partial void OnDefinitionChanging(global::System.String value);
		partial void OnDefinitionChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public global::System.String Autres
		{
			get
			{
				return _Autres;
			}
			set
			{
				OnAutresChanging(value);
				ReportPropertyChanging("Autres");
				_Autres = StructuralObject.SetValidValue(value, true);
				ReportPropertyChanged("Autres");
				OnAutresChanged();
			}
		}
		private global::System.String _Autres;
		partial void OnAutresChanging(global::System.String value);
		partial void OnAutresChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public Nullable<global::System.Int64> IDLien
		{
			get
			{
				return _IDLien;
			}
			set
			{
				OnIDLienChanging(value);
				ReportPropertyChanging("IDLien");
				_IDLien = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("IDLien");
				OnIDLienChanged();
			}
		}
		private Nullable<global::System.Int64> _IDLien;
		partial void OnIDLienChanging(Nullable<global::System.Int64> value);
		partial void OnIDLienChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public global::System.String Lien
		{
			get
			{
				return _Lien;
			}
			set
			{
				OnLienChanging(value);
				ReportPropertyChanging("Lien");
				_Lien = StructuralObject.SetValidValue(value, true);
				ReportPropertyChanged("Lien");
				OnLienChanged();
			}
		}
		private global::System.String _Lien;
		partial void OnLienChanging(global::System.String value);
		partial void OnLienChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
		[DataMemberAttribute()]
		public global::System.Boolean isInvariable
		{
			get
			{
				return _isInvariable;
			}
			set
			{
				OnisInvariableChanging(value);
				ReportPropertyChanging("isInvariable");
				_isInvariable = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("isInvariable");
				OnisInvariableChanged();
			}
		}
		private global::System.Boolean _isInvariable;
		partial void OnisInvariableChanging(global::System.Boolean value);
		partial void OnisInvariableChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public Nullable<global::System.Int64> Conjugaison
		{
			get
			{
				return _Conjugaison;
			}
			set
			{
				OnConjugaisonChanging(value);
				ReportPropertyChanging("Conjugaison");
				_Conjugaison = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("Conjugaison");
				OnConjugaisonChanged();
			}
		}
		private Nullable<global::System.Int64> _Conjugaison;
		partial void OnConjugaisonChanging(Nullable<global::System.Int64> value);
		partial void OnConjugaisonChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public Nullable<global::System.Int64> Conjugaison2
		{
			get
			{
				return _Conjugaison2;
			}
			set
			{
				OnConjugaison2Changing(value);
				ReportPropertyChanging("Conjugaison2");
				_Conjugaison2 = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("Conjugaison2");
				OnConjugaison2Changed();
			}
		}
		private Nullable<global::System.Int64> _Conjugaison2;
		partial void OnConjugaison2Changing(Nullable<global::System.Int64> value);
		partial void OnConjugaison2Changed();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
		[DataMemberAttribute()]
		public global::System.Boolean isListe
		{
			get
			{
				return _isListe;
			}
			set
			{
				OnisListeChanging(value);
				ReportPropertyChanging("isListe");
				_isListe = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("isListe");
				OnisListeChanged();
			}
		}
		private global::System.Boolean _isListe;
		partial void OnisListeChanging(global::System.Boolean value);
		partial void OnisListeChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
		[DataMemberAttribute()]
		public global::System.Boolean isAccord
		{
			get
			{
				return _isAccord;
			}
			set
			{
				OnisAccordChanging(value);
				ReportPropertyChanging("isAccord");
				_isAccord = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("isAccord");
				OnisAccordChanged();
			}
		}
		private global::System.Boolean _isAccord;
		partial void OnisAccordChanging(global::System.Boolean value);
		partial void OnisAccordChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public Nullable<global::System.Int64> Regle
		{
			get
			{
				return _Regle;
			}
			set
			{
				OnRegleChanging(value);
				ReportPropertyChanging("Regle");
				_Regle = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("Regle");
				OnRegleChanged();
			}
		}
		private Nullable<global::System.Int64> _Regle;
		partial void OnRegleChanging(Nullable<global::System.Int64> value);
		partial void OnRegleChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
		[DataMemberAttribute()]
		public global::System.Boolean isExported
		{
			get
			{
				return _isExported;
			}
			set
			{
				OnisExportedChanging(value);
				ReportPropertyChanging("isExported");
				_isExported = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("isExported");
				OnisExportedChanged();
			}
		}
		private global::System.Boolean _isExported;
		partial void OnisExportedChanging(global::System.Boolean value);
		partial void OnisExportedChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = false)]
		[DataMemberAttribute()]
		public global::System.Boolean isODS5
		{
			get
			{
				return _isODS5;
			}
			set
			{
				OnisODS5Changing(value);
				ReportPropertyChanging("isODS5");
				_isODS5 = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("isODS5");
				OnisODS5Changed();
			}
		}
		private global::System.Boolean _isODS5;
		partial void OnisODS5Changing(global::System.Boolean value);
		partial void OnisODS5Changed();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public global::System.Byte[] DefinitionCrypted
		{
			get
			{
				return StructuralObject.GetValidValue(_DefinitionCrypted);
			}
			set
			{
				OnDefinitionCryptedChanging(value);
				ReportPropertyChanging("DefinitionCrypted");
				_DefinitionCrypted = StructuralObject.SetValidValue(value, true);
				ReportPropertyChanged("DefinitionCrypted");
				OnDefinitionCryptedChanged();
			}
		}
		private global::System.Byte[] _DefinitionCrypted;
		partial void OnDefinitionCryptedChanging(global::System.Byte[] value);
		partial void OnDefinitionCryptedChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public Nullable<global::System.Boolean> Hidden
		{
			get
			{
				return _Hidden;
			}
			set
			{
				OnHiddenChanging(value);
				ReportPropertyChanging("Hidden");
				_Hidden = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("Hidden");
				OnHiddenChanged();
			}
		}
		private Nullable<global::System.Boolean> _Hidden;
		partial void OnHiddenChanging(Nullable<global::System.Boolean> value);
		partial void OnHiddenChanged();

		#endregion


		#region Navigation Properties

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[XmlIgnoreAttribute()]
		[SoapIgnoreAttribute()]
		[DataMemberAttribute()]
		[EdmRelationshipNavigationPropertyAttribute("DicoFRModel", "FK_Mots_0", "Mots")]
		public Mot Mot1
		{
			get
			{
				return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mot>("DicoFRModel.FK_Mots_0", "Mots").Value;
			}
			set
			{
				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mot>("DicoFRModel.FK_Mots_0", "Mots").Value = value;
			}
		}
		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[BrowsableAttribute(false)]
		[DataMemberAttribute()]
		public EntityReference<Mot> Mot1Reference
		{
			get
			{
				return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Mot>("DicoFRModel.FK_Mots_0", "Mots");
			}
			set
			{
				if ((value != null))
				{
					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Mot>("DicoFRModel.FK_Mots_0", "Mots", value);
				}
			}
		}

		#endregion

	}

	/// <summary>
	/// No Metadata Documentation available.
	/// </summary>
	[EdmEntityTypeAttribute(NamespaceName = "DicoFRModel", Name = "Mot")]
	[Serializable()]
	[DataContractAttribute(IsReference = true)]
	public partial class Mot : EntityObject
	{
		#region Factory Method

		/// <summary>
		/// Create a new Mot object.
		/// </summary>
		/// <param name="motID">Initial value of the MotID property.</param>
		public static Mot CreateMot(global::System.Int64 motID)
		{
			Mot mot = new Mot();
			mot.MotID = motID;
			return mot;
		}

		#endregion

		#region Primitive Properties

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = true, IsNullable = false)]
		[DataMemberAttribute()]
		public global::System.Int64 MotID
		{
			get
			{
				return _MotID;
			}
			set
			{
				if (_MotID != value)
				{
					OnMotIDChanging(value);
					ReportPropertyChanging("MotID");
					_MotID = StructuralObject.SetValidValue(value);
					ReportPropertyChanged("MotID");
					OnMotIDChanged();
				}
			}
		}
		private global::System.Int64 _MotID;
		partial void OnMotIDChanging(global::System.Int64 value);
		partial void OnMotIDChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public Nullable<global::System.Int64> DicoId
		{
			get
			{
				return _DicoId;
			}
			set
			{
				OnDicoIdChanging(value);
				ReportPropertyChanging("DicoId");
				_DicoId = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("DicoId");
				OnDicoIdChanged();
			}
		}
		private Nullable<global::System.Int64> _DicoId;
		partial void OnDicoIdChanging(Nullable<global::System.Int64> value);
		partial void OnDicoIdChanged();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public global::System.String Mot1
		{
			get
			{
				return _Mot1;
			}
			set
			{
				OnMot1Changing(value);
				ReportPropertyChanging("Mot1");
				_Mot1 = StructuralObject.SetValidValue(value, true);
				ReportPropertyChanged("Mot1");
				OnMot1Changed();
			}
		}
		private global::System.String _Mot1;
		partial void OnMot1Changing(global::System.String value);
		partial void OnMot1Changed();

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[EdmScalarPropertyAttribute(EntityKeyProperty = false, IsNullable = true)]
		[DataMemberAttribute()]
		public Nullable<global::System.Int64> Type
		{
			get
			{
				return _Type;
			}
			set
			{
				OnTypeChanging(value);
				ReportPropertyChanging("Type");
				_Type = StructuralObject.SetValidValue(value);
				ReportPropertyChanged("Type");
				OnTypeChanged();
			}
		}
		private Nullable<global::System.Int64> _Type;
		partial void OnTypeChanging(Nullable<global::System.Int64> value);
		partial void OnTypeChanged();

		#endregion


		#region Navigation Properties

		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[XmlIgnoreAttribute()]
		[SoapIgnoreAttribute()]
		[DataMemberAttribute()]
		[EdmRelationshipNavigationPropertyAttribute("DicoFRModel", "FK_Mots_0", "Dico")]
		public Dico Dico
		{
			get
			{
				return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dico>("DicoFRModel.FK_Mots_0", "Dico").Value;
			}
			set
			{
				((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dico>("DicoFRModel.FK_Mots_0", "Dico").Value = value;
			}
		}
		/// <summary>
		/// No Metadata Documentation available.
		/// </summary>
		[BrowsableAttribute(false)]
		[DataMemberAttribute()]
		public EntityReference<Dico> DicoReference
		{
			get
			{
				return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Dico>("DicoFRModel.FK_Mots_0", "Dico");
			}
			set
			{
				if ((value != null))
				{
					((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Dico>("DicoFRModel.FK_Mots_0", "Dico", value);
				}
			}
		}

		#endregion

	}

	#endregion


}
